Dep check is better now

diff --git a/periwinkle b/periwinkle
--- a/periwinkle
+++ b/periwinkle
@@ -2,13 +2,43 @@
 
 # Check if the necessary dependencies are installed
 function whichone() {
-	if [ $cmd = "nc" ]; then
-		echo "Error: 'openbsd-netcat' or 'gnu-netcat' is required but not found. Please install it."
-		exit 1
-	else
-		echo "Error: '$cmd' is required but not found. Please install it."
-		exit 1
-	fi
+	case $cmd in
+		"notify-send")
+			echo "Error: 'notify-send' (libnotify) is required but not found. Please install it."
+			exit 1
+		;;
+		"nc")
+			echo "Error: 'nc' (openbsd-netcat or gnu-netcat) is required but not found. Please install it."
+			exit 1
+		;;
+		"awk")
+			echo "Error: 'awk' is required but not found. Please install it."
+			exit 1
+		;;
+		"sed")
+			echo "Error: 'notify-send' (libnotify) is required but not found. Please install it."
+			exit 1
+		;;
+	esac
+#	if [ $cmd = "notify-send" ]; then
+#		echo "Error: 'notify-send' (libnotify) is required but not found. Please install it."
+#	fi
+#
+#	if [ $cmd = "nc" ]; then
+#		echo "Error: 'nc' (openbsd-netcat or gnu-netcat) is required but not found. Please install it."
+#		exit 1
+#	fi
+#
+#	if [ $cmd = "awk" ]; then
+#		echo "Error: 'awk' is required but not found. Please install it."
+#		exit 1
+#	fi
+#
+#	if [ $cmd = "sed" ]; then
+#		echo "Error: 'sed' s required but not found. Please install it."
+#		exit 1
+#	fi
+	
 }
 
 dependencies=("sed" "nc" "awk" "notify-send")
@@ -55,8 +85,7 @@ function help()
 	echo "more features in the future."
 }
 
-function error()
-{
+function error() {
     echo "Error: $* is not a known command >.<"
 }
 
